name: Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build tests
        run: |
          cd tests/unit
          mkdir build && cd build
          cmake ..
          cmake --build . --config release --parallel
          

      - name: Run unit tests
        run: |
          cd tests/unit/build/bin/Release
          ./unit_tests
          