name: Unit Tests

on:
  workflow_dispatch:
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          mkdir build && cd build
          cmake ..
          cmake --install . --config release --prefix install

      - name: Build tests
        run: |
          cd tests/unit
          mkdir build && cd build
          cmake -DCMAKE_PREFIX_PATH="${{ github.workspace }}/build/install" ..
          cmake --build . --config release --parallel

      - name: Run unit tests
        run: |
          cd tests/unit/build
          ./unit_tests
          